apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals-pvc
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
