apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photoprism

resources:
  - ingress/photoprism-ingress.yml
  - namespace/photoprism-namespace.yml
  - secrets/ingress-secrets.yml
  - secrets/mariadb-secrets.yml
  - secrets/photoprism-secrets.yml
  - service/mariadb-service.yml
  - service/photoprism-service.yml
  - statefulset/mariadb-statefulset.yml
  - statefulset/photoprism-statefulset.yml
  - pvc/mariadb-pvc.yml
  - pvc/photoprism-originals-pvc.yml
  - pvc/photoprism-import-pvc.yml
  - pvc/photoprism-storage-pvc.yml

