apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism-statefulset
  namespace: photoprism
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        env:
        - name: PHOTOPRISM_DEBUG
          value: "true"
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
        - mountPath: /photoprism/originals
          name: originals
        - mountPath: /photoprism/import
          name: import
        - mountPath: /photoprism/storage
          name: storage
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: http
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "750m"
      volumes:
      - name: originals
        persistentVolumeClaim:
          claimName: photoprism-originals-pvc
        # nfs:
        #   path: "Your NFS mount path"
        #   server: "Your Server Name"
      - name: import
        persistentVolumeClaim:
          claimName: photoprism-import-pvc
      - name: storage
        persistentVolumeClaim:
          claimName: photoprism-storage-pvc
