apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: photoprism
spec:
  clusterIP: 10.43.0.11  
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP

