apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: photoprism
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changeme
  MYSQL_USER: photoprism
  MYSQL_PASSWORD: changeme
  MYSQL_DATABASE: photoprism
