apiVersion: v1
kind: Secret
metadata:
  name: photoprism-secrets
  namespace: photoprism
stringData:
  PHOTOPRISM_ADMIN_PASSWORD: changeme
  PHOTOPRISM_DATABASE_DSN: photoprism:changeme@tcp(mariadb-service:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true
